using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HollowTwitch.Commands
{
    public class ChineseCommand
    {
        /*public static readonly Dictionary<string, string> CmdTranslation = new Dictionary<string, string>
        {
{"ax2uBlind","摸黑"},
{"nopogo","禁下劈"},
{"conveyor","传送带"},
{"jumplength","跳跃距离"},
{"lifeblood","蓝血"},
{"godmode","上帝模式"},
{"sleep","睡眠"},
{"limitSoul","锁魂"},
{"jumpspeed","跳跃速度"},
{"wind","风"},
{"dashSpeed","冲刺速度"},
{"dashLength","冲刺距离"},
{"dashVector","冲刺方向"},
{"triplejump","三段跳"},
{"overflow","护符过载"},
{"timescale","变速"},
{"gravity","改变重力"},
{"invertcontrols","方向键颠倒"},
{"slippery","地面光滑"},
{"nailscale","骨钉尺寸+"},
{"bindings","四锁"},
{"float","无重力"},
{"Salubra","祝福"},
{"hwurmpU","彩蛋"},
{"walkspeed","移动速度"},
{"geo","吉欧"},
{"respawn","重生"},
{"knockback",""},
{"slaphand","巨力之手"},
{"toggle","能力+"},
{"doubledamage","倍伤"},
{"spawn","小怪"},
{"jars","收藏加"},
{"spawnpv","纯粹容器"},
{"revek","守墓人"},
{"duplicateboss","复制BOSS"},
{"spawnshade","阴影"},
{"communism","敌人血量减半"},
{"zap","追踪电"},
{"bees","小蜜蜂"},
{"lasers","激光"},
{"spikefloor","梦魇地刺"},
{"cameffect","镜头+"},
{"setText","设置文本+"},
{"heal","回血"},
{"rng","混乱"},
{"sfxRando","随机音效"},
{"blacklist","禁止命令+"},
{"allowCommand","开启命令+"},
{"ban","禁言+"},
{"unban","取消禁言+"},
{"timeout","暂时屏蔽+"},
{"Invert","颠倒"},
{"Flip","翻转"},
{"Nausea","晕眩"},
{"Backwards","倒放"},
{"Mirror","镜像"},
{"Pixelate","像素化"},
{"Zoom","变焦"},
        };
        */
        public static readonly Dictionary<string, string> CmdTranslation = new Dictionary<string, string>
        {
{"摸黑","ax2uBlind"},
{"禁下劈","nopogo"},
{"传送带","conveyor"},
{"跳跃距离","jumplength"},
{"蓝血","lifeblood"},
{"上帝模式","godmode"},
{"睡眠","sleep"},
{"锁魂","limitSoul"},
{"跳跃速度","jumpspeed"},
{"风","wind"},
{"冲刺速度","dashSpeed"},
{"冲刺距离","dashLength"},
{"冲刺方向","dashVector"},
{"三段跳","triplejump"},
{"满魂","overflow"},
{"变速","timescale"},
{"改变重力","gravity"},
{"方向键颠倒","invertcontrols"},
{"地面光滑","slippery"},
{"骨钉尺寸","nailscale"},
{"大钉钉","nailscale 4"},
{"大丁丁","nailscale 4"},
{"小钉钉","nailscale 0.5"},
{"小丁丁","nailscale 0.5"},
{"四锁","bindings"},
{"无重力","float"},
{"祝福","Salubra"},
{"彩蛋","hwurmpU"},
{"移动速度","walkspeed"},
{"吉欧","geo"},
{"重生","respawn"},
//{"","knockback"},
{"巨力之手","slaphand"},
{"能力","toggle"},
{"倍伤","doubledamage"},
{"小怪","spawn"},
{"收藏加","jars"},
{"纯粹容器","spawnpv"},
{"守墓人","revek"},
{"复制BOSS","duplicateboss"},
{"阴影","spawnshade"},
{"敌人血量减半","communism"},
{"追踪电","zap"},
{"小蜜蜂","bees"},
{"激光","lasers"},
{"梦魇地刺","spikefloor"},
{"镜头","cameffect"},
{"设置文本","setText"},
{"回血","heal"},
{"混乱","rng"},
{"随机音效","sfxRando"},
{"禁止命令","blacklist"},
{"开启命令","allowCommand"},
{"禁言","ban"},
{"取消禁言","unban"},
{"暂时屏蔽","timeout"},
{"颠倒"," Invert"},
{"负片"," Flip"},
{"晕眩"," Nausea"},
{"倒放"," Backwards"},
{"镜像"," Mirror"},
{"像素化"," Pixelate"},
{"变焦"," Zoom"},
{"滚滚"," roller"},
{"古神"," aspid"},
        };
    
    }
}
