using System.Collections.Generic;

namespace HollowTwitch.Commands
{
    public static class ChineseCommand
    {
        public static readonly Dictionary<string, string> CmdTranslation = new Dictionary<string, string>
        {
            { "摸黑", "ax2uBlind" },
            { "禁下劈", "nopogo" },
            { "传送带", "conveyor" },
            { "跳跃距离", "jumplength" },
            { "蓝血", "lifeblood" },
            { "上帝模式", "godmode" },
            { "睡眠", "sleep" },
            { "锁魂", "limitSoul" },
            { "跳跃速度", "jumpspeed" },
            { "风", "wind" },
            { "冲刺速度", "dashSpeed" },
            { "冲刺距离", "dashLength" },
            { "冲刺方向", "dashVector" },
            { "三段跳", "triplejump" },
            { "满魂", "overflow" },
            { "变速", "timescale" },
            { "改变重力", "gravity" },
            { "方向键颠倒", "invertcontrols" },
            { "地面光滑", "slippery" },
            { "骨钉尺寸", "nailscale" },
            { "大钉钉", "nailscale 4" },
            { "大丁丁", "nailscale 4" },
            { "小钉钉", "nailscale 0.5" },
            { "小丁丁", "nailscale 0.5" },
            { "四锁", "bindings" },
            { "无重力", "float" },
            { "祝福", "Salubra" },
            { "彩蛋", "hwurmpU" },
            { "移动速度", "walkspeed" },
            { "吉欧", "geo" },
            { "重生", "respawn" },
            //{"","knockback"},
            { "巨力之手", "slaphand" },
            { "能力", "toggle" },
            { "倍伤", "doubledamage" },
            { "小怪", "spawn" },
            { "收藏加", "jars" },
            { "纯粹容器", "spawnpv" },
            { "守墓人", "revek" },
            { "复制BOSS", "duplicateboss" },
            { "阴影", "spawnshade" },
            { "敌人血量减半", "communism" },
            { "追踪电", "zap" },
            { "小蜜蜂", "bees" },
            { "激光", "lasers" },
            { "梦魇地刺", "spikefloor" },
            { "镜头", "cameffect" },
            { "设置文本", "setText" },
            { "回血", "heal" },
            { "混乱", "rng" },
            { "随机音效", "sfxRando" },
            { "禁止命令", "blacklist" },
            { "开启命令", "allowCommand" },
            { "禁言", "ban" },
            { "取消禁言", "unban" },
            { "暂时屏蔽", "timeout" },
            { "颠倒", " Invert" },
            { "负片", " Flip" },
            { "晕眩", " Nausea" },
            { "倒放", " Backwards" },
            { "镜像", " Mirror" },
            { "像素化", " Pixelate" },
            { "变焦", " Zoom" },
            { "滚滚", " roller" },
            { "古神", " aspid" },
        };
    }
}